# -*- coding: utf-8 -*-
"""Cars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R9m1PrSqpjI-B5YDlFgFEvMN4XdKhf_W

**Cars Dataset**

Here, the data of different cars is given with their applications.
This data is available as a csv file. We are going to analyze the data set using the pandas dataframe
"""

import pandas as pd

car = pd.read_csv('/content/2. Cars Data1.csv')
car.head()

car.shape

"""1). Instruction (For Data Cleaning)


*   Find All null values in the dataset. if there is any null value in any column, then fill it with the mean of that column


"""

car.isnull().sum()

car['Cylinders'].fillna(car['Cylinders'].mean(), inplace = True)

car

"""2). Question (Based on value Counts)


*   Check what are the different types of Make are there in our dataset. And what is the count (occurence) of each Make in the data?



"""

car.head(2)

car['Make'].value_counts()

"""3). Instruction (Filtering)


*   Show all the records where origin is Asia or Europe. 



"""

car.head(2)

car[car['Origin'].isin(['Asia','Europe'])]

"""4) Instruction (Removing Unwanted records)


*   Remove all the records(rows) where Weight is above 400



"""

car.head(2)

car[~(car['Weight'] > 4000)]

428 - 103

"""5) Instruction (Applying function on a column)


*   Increase all the values of 'MPG_city' column by 3



"""

car.head(2)

car['MPG_City'] = car['MPG_City'].apply(lambda x:x+3)

car